[package]
name = "ff"
version = "0.1.0"
authors = ["Aurelien Gateau <mail@agateau.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.2.10"
globset = "0.4.4"
